### ISSUE TITLE
按README配置后执行失败

### ISSUE THREAD

**Issue by yanranxiaoxi** [xirikm/hostloc-auto-get-points#13]
我的配置路线：
1. 设置两个 Secrets；
2. 进入 Action 并点击绿色 "I understand..." 按钮；
3. 修改 README.md；
4. 进入 Action --> Re-run jobs；

返回的 Get points：
    Run python hostloc_get_points.py
    共检测到 1 个帐户，开始获取积分
    ******************************
    第 1 个帐户登录失败！
    请检查你的帐户是否正确！
    ******************************
    程序执行完毕，获取积分过程结束

其他可能有帮助：
1. 我的用户名为全中文，密码 32 位并包含 -?=+*-($ 符号；
2. 我尝试过使用中文用户名以及邮箱作为用户名，执行后都返回相同的内容：“第 1 个账户登陆失败！”；

**Comment by xirikm** [comment]
中文用户名是没有关系的，我自己也是中文用户名，只要用户名和密码中没有半角逗号 `,` 就行了（那样会被认为是两个帐号/密码）

我刚刚试了，我这边是能正常运行的（在这个时段），从你的描述中我也看不出哪里出了问题🙃，检查一下设置的 Secrets 项的名字对不对？或者换个帐号试试（如果有的话）？

**Comment by justcopy** [comment]
偶尔会登陆失败，不清楚什么问题

**Comment by xirikm** [comment]
> 偶尔会登陆失败，不清楚什么问题

loc 提高的封禁的严格程度，我正在调整代码，另外你们可能需要自己改一下运行时间，不要全部挤在凌晨1点（GitHub Actions 极有可能是多个虚拟机共用一个出口 ip 地址，大量 Fork 本仓库的 GitHub Actions 任务在同一时间运行时，可能会出现多个任务使用同一个 ip 地址的情况，这样即使单个任务设置的请求时间间隔已经足够长，对该 ip 地址而言仍有可能会出现请求速度过快被封禁的情况）
