### ISSUE TITLE
日志问题

### ISSUE THREAD

**Issue by majianyu2007** [xirikm/hostloc-auto-get-points#17]
``Run python hostloc_get_points.py
当前使用 ip 地址：52.xxx.xxx.17x
共检测到 1 个帐户，开始获取积分
******************************
程序执行异常：400 Client Error: Bad Request for url: https://www.hostloc.com/home.php?mod=spacecp
******************************
程序执行完毕，获取积分过程结束

**Comment by xirikm** [comment]
这个一般来说就是触发了loc的防御机制，换个时间再执行就好了

**Comment by majianyu2007** [comment]
好的，谢谢
