### ISSUE TITLE
job有前后依赖关系的如何解决【解决】

### ISSUE THREAD

**Issue by hzbd** [xirikm/hostloc-auto-get-points#18]
![image](https://user-images.githubusercontent.com/3000843/89489473-2fec9700-d7dd-11ea-980e-269a219c0a26.png)

首先感谢，我的github action使用姿势学习是通过你的这个项目上手的。

这个问题可解决，使用`needs`参数，参考如下：

```
deploy-job: # deploy job is for deploying our code to google cloud cluster.
    runs-on: ubuntu-latest
    needs: [package-job]  # ***will require package-job to be successful for triggering ***
```

**Comment by xirikm** [comment]
我这里的“某个链接/帐户访问出错时不中断程序继续尝试下一个”是在 Python 脚本中实现的，GitHub Actions 总共只有一个 job ，没有依赖关系啊。

GitHub Actions 是通过程序返回的状态码来判断任务是否执行成功的（一般来说 0 表示正常退出）。  
Python 执行脚本文件时如果遇到错误会提前结束程序（停止执行后续代码）并返回一个异常状态码，我这里不可能说某个链接访问出错那后面的链接就都不试了，多帐户支持也需要考虑不能因为前一个帐户出问题导致后面的帐户无法执行，所以我在程序中把所有的这些错误都捕获了，不让程序异常退出，脚本至始至终都能执行到最后，然后正常退出（返回状态码 0），所以对 GitHub Actions 来说任务永远都是通过。

**Comment by xirikm** [comment]
倒是可以通过记录脚本执行到`except`域中的次数，不为 0 时在脚本最后手动`sys.exit(1)`退出，从而让 GitHub Actions 认为任务执行失败。不过这样感觉也没什么意义，所以没有搞😂

**Comment by hzbd** [comment]
> 我这里的“某个链接/帐户访问出错时不中断程序继续尝试下一个”是在 Python 脚本中实现的，GitHub Actions 总共只有一个 job ，没有依赖关系啊。
> 
> GitHub Actions 是通过程序返回的状态码来判断任务是否执行成功的（一般来说 0 表示正常退出）。
> Python 执行脚本文件时如果遇到错误会提前结束程序（停止执行后续代码）并返回一个异常状态码，我这里不可能说某个链接访问出错那后面的链接就都不试了，多帐户支持也需要考虑不能因为前一个帐户出问题导致后面的帐户无法执行，所以我在程序中把所有的这些错误都捕获了，不让程序异常退出，脚本至始至终都能执行到最后，然后正常退出（返回状态码 0），所以对 GitHub Actions 来说任务永远都是通过。

-------
哦 理解偏差 不是多step有顺序执行。
