### ISSUE TITLE
actions异常

### ISSUE THREAD

**Issue by Xiefengshang** [xirikm/hostloc-auto-get-points#19]
RT，老哥你的actions结果也是这样
程序执行异常：400 Client Error: Bad Request for url: https://www.hostloc.com/home.php?mod=spacecp

**Comment by xirikm** [comment]
CN2 GIA 线路爆炸，论坛开防御了，等什么时候防御关了就正常了，这段时间有需要的话手动签一下吧。

**Comment by xirikm** [comment]
这问题换无头浏览器去请求的话应该能解决，但是就这么个简单的功能我不想搞太复杂了，所以目前不打算修改。

**Comment by Xiefengshang** [comment]
> 这问题换无头浏览器去请求的话应该能解决，但是就签到这么个简单的功能我不想搞太复杂了，所以目前不打算修改。

好的，谢谢答复
