### ISSUE TITLE
点击action后没有出现和作者一样的界面啊

### ISSUE THREAD

**Issue by guohaiping** [xirikm/hostloc-auto-get-points#3]
![QQ截图20200312110940](https://user-images.githubusercontent.com/12585681/76483552-42db8500-6452-11ea-89b0-c15bd9c33598.jpg)
![QQ截图20200312111041](https://user-images.githubusercontent.com/12585681/76483555-453ddf00-6452-11ea-9f07-e2284ec06a05.jpg)

**Comment by guohaiping** [comment]
选择哪个？

**Comment by xirikm** [comment]
这个界面是已经在这个仓库启用了Github Actions了啊。
你随便改点什么提交一下，然后再点进来，有构建记录就没问题了
